"""Hằng số định nghĩa giới hạn độ dài trường dữ liệu trong CSDL."""

MAX_USERNAME_LENGTH = 100
MAX_EMAIL_LENGTH = 255
MAX_NAME_LENGTH = 255
MAX_TITLE_LENGTH = 255
MAX_DOMAIN_LENGTH = 100
MAX_STATUS_LENGTH = 30
MAX_ROLE_LENGTH = 30
MAX_TYPE_LENGTH = 50
MAX_METRIC_LENGTH = 255
MAX_DIMENSION_LENGTH = 255
MAX_GRANULARITY_LENGTH = 50
MAX_AGGREGATION_LENGTH = 50
