"""Định nghĩa danh sách Error Codes chuẩn của toàn bộ hệ thống backend."""

from enum import StrEnum


class ErrorCode(StrEnum):
    """Mã lỗi chuẩn hóa cho toàn hệ thống (dạng UPPER_SNAKE_CASE)."""

    # --- Business Domain Error Codes ---
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    REQUIREMENT_NOT_FOUND = "REQUIREMENT_NOT_FOUND"
    DATA_SOURCE_NOT_FOUND = "DATA_SOURCE_NOT_FOUND"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    DATA_MODEL_NOT_FOUND = "DATA_MODEL_NOT_FOUND"
    PROPOSAL_NOT_FOUND = "PROPOSAL_NOT_FOUND"

    REVISION_CONFLICT = "REVISION_CONFLICT"
    PROPOSAL_CONFLICT = "PROPOSAL_CONFLICT"
    PROPOSAL_OUTDATED = "PROPOSAL_OUTDATED"

    INVALID_REQUIREMENT = "INVALID_REQUIREMENT"
    INVALID_DATA_MODEL = "INVALID_DATA_MODEL"

    # --- Domain Validation Error Codes ---
    # User Domain
    INVALID_EMAIL = "INVALID_EMAIL"
    INVALID_USERNAME = "INVALID_USERNAME"
    USERNAME_TOO_LONG = "USERNAME_TOO_LONG"
    INVALID_PASSWORD = "INVALID_PASSWORD"

    # Project Domain
    INVALID_PROJECT_NAME = "INVALID_PROJECT_NAME"
    PROJECT_NAME_TOO_LONG = "PROJECT_NAME_TOO_LONG"
    PROJECT_NAME_ALREADY_EXISTS = "PROJECT_NAME_ALREADY_EXISTS"
    INVALID_PROJECT_REQUIREMENT = "INVALID_PROJECT_REQUIREMENT"
    INVALID_PROJECT_STATUS_TRANSITION = "INVALID_PROJECT_STATUS_TRANSITION"

    # Requirement Domain
    INVALID_REQUIREMENT_TITLE = "INVALID_REQUIREMENT_TITLE"
    REQUIREMENT_TITLE_TOO_LONG = "REQUIREMENT_TITLE_TOO_LONG"
    INVALID_REQUIREMENT_DESCRIPTION = "INVALID_REQUIREMENT_DESCRIPTION"

    # Analytical Requirement Domain
    INVALID_ANALYTICAL_REQUIREMENT_REF = "INVALID_ANALYTICAL_REQUIREMENT_REF"

    # Data Source Domain
    INVALID_DATA_SOURCE_NAME = "INVALID_DATA_SOURCE_NAME"
    DATA_SOURCE_NAME_TOO_LONG = "DATA_SOURCE_NAME_TOO_LONG"
    INVALID_DATA_SOURCE_LOCATION = "INVALID_DATA_SOURCE_LOCATION"

    # Agent Session Domain
    INVALID_SESSION_EVENT_REF = "INVALID_SESSION_EVENT_REF"

    # Data Model Domain
    INVALID_DBML_CONTENT = "INVALID_DBML_CONTENT"
    INVALID_PROPOSAL_STATUS_TRANSITION = "INVALID_PROPOSAL_STATUS_TRANSITION"

    # Sandbox Domain
    SANDBOX_CONFIG_NOT_FOUND = "SANDBOX_CONFIG_NOT_FOUND"
    SANDBOX_CONNECTION_FAILED = "SANDBOX_CONNECTION_FAILED"
    SANDBOX_EXECUTION_ERROR = "SANDBOX_EXECUTION_ERROR"
    INVALID_SANDBOX_CONFIG = "INVALID_SANDBOX_CONFIG"
    UNSUPPORTED_SANDBOX_DB_TYPE = "UNSUPPORTED_SANDBOX_DB_TYPE"
    UNSUPPORTED_DDL_DIALECT = "UNSUPPORTED_DDL_DIALECT"

    # --- General Validation Error Code ---
    VALIDATION_ERROR = "VALIDATION_ERROR"

    # --- Authentication Error Codes ---
    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"

    # --- Authorization Error Code ---
    PERMISSION_DENIED = "PERMISSION_DENIED"

    # --- System / Infrastructure Error Codes ---
    DATABASE_ERROR = "DATABASE_ERROR"
    REDIS_ERROR = "REDIS_ERROR"
    STORAGE_ERROR = "STORAGE_ERROR"

    LLM_ERROR = "LLM_ERROR"
    AGENT_EXECUTION_ERROR = "AGENT_EXECUTION_ERROR"

    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"

    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
