"""Ánh xá tập trung từ ErrorCode sang HTTP Status Code tương ứng."""

from http import HTTPStatus

from src.common.exceptions.error_codes import ErrorCode

ERROR_STATUS_MAP: dict[ErrorCode, HTTPStatus] = {
    # --- Business Domain Errors ---
    ErrorCode.RESOURCE_NOT_FOUND: HTTPStatus.NOT_FOUND,
    ErrorCode.USER_NOT_FOUND: HTTPStatus.NOT_FOUND,
    ErrorCode.PROJECT_NOT_FOUND: HTTPStatus.NOT_FOUND,
    ErrorCode.REQUIREMENT_NOT_FOUND: HTTPStatus.NOT_FOUND,
    ErrorCode.DATA_SOURCE_NOT_FOUND: HTTPStatus.NOT_FOUND,
    ErrorCode.SESSION_NOT_FOUND: HTTPStatus.NOT_FOUND,
    ErrorCode.DATA_MODEL_NOT_FOUND: HTTPStatus.NOT_FOUND,
    ErrorCode.PROPOSAL_NOT_FOUND: HTTPStatus.NOT_FOUND,
    ErrorCode.REVISION_CONFLICT: HTTPStatus.CONFLICT,
    ErrorCode.PROPOSAL_CONFLICT: HTTPStatus.CONFLICT,
    ErrorCode.PROPOSAL_OUTDATED: HTTPStatus.CONFLICT,
    ErrorCode.INVALID_REQUIREMENT: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_DATA_MODEL: HTTPStatus.UNPROCESSABLE_ENTITY,
    # --- Domain Validation Errors ---
    ErrorCode.INVALID_EMAIL: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_USERNAME: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.USERNAME_TOO_LONG: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_PASSWORD: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_PROJECT_NAME: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.PROJECT_NAME_TOO_LONG: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.PROJECT_NAME_ALREADY_EXISTS: HTTPStatus.CONFLICT,
    ErrorCode.INVALID_PROJECT_REQUIREMENT: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_PROJECT_STATUS_TRANSITION: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_REQUIREMENT_TITLE: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.REQUIREMENT_TITLE_TOO_LONG: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_REQUIREMENT_DESCRIPTION: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_ANALYTICAL_REQUIREMENT_REF: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_DATA_SOURCE_NAME: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.DATA_SOURCE_NAME_TOO_LONG: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_DATA_SOURCE_LOCATION: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_SESSION_EVENT_REF: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_DBML_CONTENT: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_PROPOSAL_STATUS_TRANSITION: HTTPStatus.UNPROCESSABLE_ENTITY,
    # --- Sandbox Errors ---
    ErrorCode.SANDBOX_CONFIG_NOT_FOUND: HTTPStatus.NOT_FOUND,
    ErrorCode.SANDBOX_CONNECTION_FAILED: HTTPStatus.BAD_REQUEST,
    ErrorCode.SANDBOX_EXECUTION_ERROR: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_SANDBOX_CONFIG: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.UNSUPPORTED_SANDBOX_DB_TYPE: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.UNSUPPORTED_DDL_DIALECT: HTTPStatus.UNPROCESSABLE_ENTITY,
    # --- General Validation Errors ---
    ErrorCode.VALIDATION_ERROR: HTTPStatus.UNPROCESSABLE_ENTITY,
    # --- Authentication Errors ---
    ErrorCode.AUTHENTICATION_REQUIRED: HTTPStatus.UNAUTHORIZED,
    ErrorCode.INVALID_CREDENTIALS: HTTPStatus.UNAUTHORIZED,
    ErrorCode.TOKEN_EXPIRED: HTTPStatus.UNAUTHORIZED,
    ErrorCode.TOKEN_INVALID: HTTPStatus.UNAUTHORIZED,
    # --- Authorization Errors ---
    ErrorCode.PERMISSION_DENIED: HTTPStatus.FORBIDDEN,
    # --- System / Infrastructure Errors ---
    ErrorCode.DATABASE_ERROR: HTTPStatus.INTERNAL_SERVER_ERROR,
    ErrorCode.REDIS_ERROR: HTTPStatus.INTERNAL_SERVER_ERROR,
    ErrorCode.STORAGE_ERROR: HTTPStatus.INTERNAL_SERVER_ERROR,
    ErrorCode.LLM_ERROR: HTTPStatus.BAD_GATEWAY,
    ErrorCode.AGENT_EXECUTION_ERROR: HTTPStatus.INTERNAL_SERVER_ERROR,
    ErrorCode.EXTERNAL_SERVICE_ERROR: HTTPStatus.BAD_GATEWAY,
    ErrorCode.INTERNAL_SERVER_ERROR: HTTPStatus.INTERNAL_SERVER_ERROR,
}


def get_http_status_code(code: ErrorCode) -> HTTPStatus:
    """Trả về HTTP Status Code tương ứng với ErrorCode."""
    return ERROR_STATUS_MAP.get(code, HTTPStatus.INTERNAL_SERVER_ERROR)
